/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CaseHandlingSystem;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Isurika
 */
public class AddCase extends javax.swing.JFrame {

    /**
     * Creates new form AddCase
     */
    public AddCase() {
        initComponents();
        combos();

    }

    public void combos() {
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            String query = "select CourtNo from court";
            ps = db.con().prepareStatement(query);
            rs = ps.executeQuery(query);
            while (rs.next()) {
                courtno.addItem(rs.getString("CourtNo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddCase2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CaseId = new javax.swing.JTextField();
        CaseNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CaseDes = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ClientId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Evidence = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        courtno = new javax.swing.JComboBox<String>();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1016, 734));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Client Id");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(100, 140, 97, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Case Id");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(100, 200, 85, 22);

        CaseId.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(CaseId);
        CaseId.setBounds(290, 200, 260, 30);

        CaseNo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(CaseNo);
        CaseNo.setBounds(290, 250, 260, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Case No");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(100, 250, 85, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Case Type");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(100, 310, 80, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Case Description");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(100, 380, 131, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Court No");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(110, 540, 74, 22);

        CaseDes.setColumns(20);
        CaseDes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CaseDes.setRows(5);
        jScrollPane1.setViewportView(CaseDes);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(290, 360, 260, 140);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Case Date");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(660, 120, 92, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(450, 610, 100, 40);

        ClientId.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(ClientId);
        ClientId.setBounds(290, 140, 260, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(830, 60, 100, 40);

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Trail");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(290, 310, 100, 31);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Evidance");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(660, 210, 80, 30);

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Call");
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(440, 310, 110, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(290, 610, 100, 40);

        Evidence.setColumns(20);
        Evidence.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Evidence.setRows(5);
        jScrollPane2.setViewportView(Evidence);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(660, 260, 270, 170);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(670, 470, 60, 22);

        jPanel3.add(courtno);
        courtno.setBounds(290, 530, 260, 30);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("New");
        jPanel3.add(jRadioButton3);
        jRadioButton3.setBounds(760, 465, 100, 30);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Pending");
        jPanel3.add(jRadioButton4);
        jRadioButton4.setBounds(760, 510, 100, 30);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Closed");
        jPanel3.add(jRadioButton5);
        jRadioButton5.setBounds(760, 560, 100, 30);
        jPanel3.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(760, 130, 155, 22);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p7.jpg"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(0, 0, 1010, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement ps = null;
        int c = 0;
        String idcl = ClientId.getText();

        if (idcl.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Client ID");
            ClientId.setText("");
        } else {
            c++;
        }
        String idcase = CaseId.getText();
        if (CaseId.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Case ID");
            CaseId.setText("");
        } else {
            c++;

        }
        String caseno = CaseNo.getText();

        if (caseno.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter case Number");
            CaseNo.setText("");
        } else {
            c++;
        }
        String ctype = null;

        if (jRadioButton1.isSelected()) {
            ctype = "Trail";
            c++;
        } else if (jRadioButton2.isSelected()) {
            ctype = "Call";
            c++;
        } else {
            JOptionPane.showMessageDialog(this, "Select the Case Type");
        }
        String cstatus = null;

        if (jRadioButton3.isSelected()) {
            cstatus = "New";
            c++;
        } else if (jRadioButton4.isSelected()) {
            cstatus = "Pending";
            c++;
        } else if (jRadioButton5.isSelected()) {
            cstatus = "Finish";
            c++;
        } else {
            JOptionPane.showMessageDialog(this, "Select the Case Status");
        }

        String casedes = CaseDes.getText();
        if (casedes.equals("")) {
            //JOptionPane.showMessageDialog(this, "Enter Description of this case");
            CaseDes.setText(null);
        } else {
           // c++;
        }

        String ts = new SimpleDateFormat("yyyy_MM_dd_HH:mm").format(dateChooserCombo1.getSelectedDate().getTime());

        String evi = Evidence.getText();

        if (c > 3) {

            String sg = "insert into AddCase values(?,?,?,?,?,?,?,?,?)";
            try {
                ps = db.con().prepareStatement(sg);
                ps.setString(1, idcase);
                ps.setString(2, caseno);
                ps.setString(3, ctype);
                ps.setString(4, casedes);
                ps.setString(5, ts);
                ps.setString(6, idcl);
                ps.setString(7, (String) courtno.getSelectedItem());
                ps.setString(8, evi);
                ps.setString(9, cstatus);
                ps.execute();
                JOptionPane.showMessageDialog(this, " Saved !");
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(this, "Clientid does not exists\nOR\nCaseID  already exists !");
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LawyerPortal ac = new LawyerPortal();
        ac.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ClientId.setText("");
        CaseId.setText("");
        CaseNo.setText("");
        CaseDes.setText("");
        Evidence.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        Calendar aDate = null;
        dateChooserCombo1.setCurrent(aDate);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CaseDes;
    private javax.swing.JTextField CaseId;
    private javax.swing.JTextField CaseNo;
    private javax.swing.JTextField ClientId;
    private javax.swing.JTextArea Evidence;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> courtno;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
