/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CaseHandlingSystem;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        caseid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        caseno = new javax.swing.JTextField();
        courtno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        search3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        clientid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        casedes = new javax.swing.JTextArea();
        date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1016, 734));
        setPreferredSize(new java.awt.Dimension(1016, 734));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Case ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 150, 96, 22);

        caseid.setEditable(false);
        caseid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(caseid);
        caseid.setBounds(230, 150, 250, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Case No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 210, 65, 22);

        caseno.setEditable(false);
        caseno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(caseno);
        caseno.setBounds(230, 210, 250, 30);

        courtno.setEditable(false);
        courtno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(courtno);
        courtno.setBounds(230, 480, 250, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Case Description");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 290, 140, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Court No");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 480, 90, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Case Date");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 530, 90, 22);

        search3.setBackground(new java.awt.Color(0, 0, 0));
        search3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        search3.setForeground(new java.awt.Color(255, 255, 255));
        search3.setText("Search");
        search3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search3ActionPerformed(evt);
            }
        });
        jPanel1.add(search3);
        search3.setBounds(680, 240, 99, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(840, 240, 96, 40);

        clientid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientidActionPerformed(evt);
            }
        });
        jPanel1.add(clientid);
        clientid.setBounds(680, 150, 250, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(830, 60, 100, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ClientID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(570, 150, 90, 30);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(360, 610, 120, 40);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case ID", "Case No", "Court Description", "Court No", "Case Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(500, 330, 460, 210);

        casedes.setEditable(false);
        casedes.setColumns(20);
        casedes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        casedes.setRows(5);
        jScrollPane2.setViewportView(casedes);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(230, 290, 250, 170);

        date.setEditable(false);
        date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date);
        date.setBounds(230, 540, 250, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p10.jpg"))); // NOI18N
        jLabel2.setText("Client ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search3ActionPerformed
        String sc = clientid.getText();
        if (sc.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter ClientID");
        }
        else{
        DefaultTableModel tb = (DefaultTableModel) table1.getModel();
        tb.setRowCount(0);
        PreparedStatement pst = null;
        ResultSet rst = null;

        String query = "SELECT * FROM AddCase WHERE ClientID LIKE ?";

        try {
            pst = db.con().prepareStatement(query);
            pst.setString(1, sc);
            rst = pst.executeQuery();
            while (rst.next()) {

                Vector v = new Vector();
                v.add(rst.getString("CaseID"));
                v.add(rst.getString("CaseNo"));
                v.add(rst.getString("Casedes"));
                v.add(rst.getString("CourtNo"));
                v.add(rst.getString("CaseDate"));

                tb.addRow(v);

            }
            if (tb.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Invalid ClientID");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                pst.close();
                rst.close();
            } catch (SQLException ex) {
                Logger.getLogger(Delete.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_search3ActionPerformed
    }

    private void clientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientidActionPerformed

    }//GEN-LAST:event_clientidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        PreparedStatement ps = null;
        String delt = caseid.getText();
        if (delt.equals("")) {
            JOptionPane.showMessageDialog(this, "Select any client before deletion!");

        } else {
            int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                String query = "DELETE FROM AddCase WHERE CaseID=?";

                clientid.setText("");
                caseid.setText("");
                caseno.setText("");
                courtno.setText("");
                casedes.setText("");
                date.setText("");
                try {
                    ps = db.con().prepareStatement(query);
                    ps.setString(1, delt);

                    ps.execute();
                } catch (SQLException ex) {
                    Logger.getLogger(Delete.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        ps.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(AddCase.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                JOptionPane.showMessageDialog(this, "Deleted");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LawyerPortal ac = new LawyerPortal();
        ac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clientid.setText("");
        caseid.setText("");
        caseno.setText("");
        courtno.setText("");
        casedes.setText("");
        date.setText("");


    }//GEN-LAST:event_jButton4ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        DefaultTableModel tb = (DefaultTableModel) table1.getModel();
        int selectedRowIndex = table1.getSelectedRow();
        caseid.setText(tb.getValueAt(selectedRowIndex, 0).toString());
        caseno.setText(tb.getValueAt(selectedRowIndex, 1).toString());
        casedes.setText(tb.getValueAt(selectedRowIndex, 2).toString());
        courtno.setText(tb.getValueAt(selectedRowIndex, 3).toString());
        date.setText(tb.getValueAt(selectedRowIndex, 4).toString());
    }//GEN-LAST:event_table1MouseClicked

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea casedes;
    private javax.swing.JTextField caseid;
    private javax.swing.JTextField caseno;
    private javax.swing.JTextField clientid;
    private javax.swing.JTextField courtno;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search3;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
